/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.sql.*;
import connection.ModuloConexao;
/**
 *
 * @author Dhiego
 */
public class TelaTransferencia extends javax.swing.JFrame {

    Connection conexao = null;
    
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    TelaLogin telogin = new TelaLogin();
    public int conta = telogin.getConta();
    public Double saldo;
    public Double saldofinal;
    public Double saldocontadestino; 
    public Double valordeposito;
    public int idcontadestino;
    public String nomedestinatario;
    
    
     public void ConsultaSaldo(){
       String sql = "Select Saldo From conta WHERE Numero = ? ";
       
       try {
           pst = conexao.prepareStatement(sql);
           pst.setInt(1, conta);
           rs = pst.executeQuery();
           
           if(rs.next()){  
               saldo = rs.getDouble(1);
               
               
           }
           
           
           
       } catch (Exception e) {
           System.out.println("Não achei");
       }
       
       
       
       
       
   }
   
   public void Retirando(){
       String sac = "Update conta SET Saldo = ? WHERE Numero = ?";
       
       try {
           pst = conexao.prepareStatement(sac);
           pst.setDouble(1, saldofinal);
           pst.setInt(2, conta);
           pst.executeUpdate();
           
           
           
           
       } catch (Exception e) {
       }
       
       
       
   }
   
   public void adicionando(){
        String adc = "Update conta SET Saldo = ? WHERE Numero = ?";
       
       try {
           pst = conexao.prepareStatement(adc);
           pst.setDouble(1, valordeposito);
           pst.setInt(2, Integer.parseInt(txtcontclientetransfer.getText()));
           pst.executeUpdate();
           
           
           
           
       } catch (Exception e) {
       }
       
       

       
   }
   
   
   public void contadestino(){
       String contad = "Select Id_Conta, Saldo FROM conta WHERE Numero = ?";
       
       try {
           pst = conexao.prepareStatement(contad);
           pst.setInt(1, Integer.parseInt(txtcontclientetransfer.getText()));
           rs = pst.executeQuery();
           
           if(rs.next()){
               idcontadestino = rs.getInt(1);
               saldocontadestino = rs.getDouble(2);
               
               
               
           }
           
           
       } catch (Exception e) {
       }
               
       
       
       
       
   }
   
   
   
   
public void pegandonome(){
    String peganome = "Select Nome From cliente WHERE Id_cliente";
    
    try {
        pst = conexao.prepareStatement(peganome);
        pst.setInt(1, idcontadestino);
        
        rs = pst.executeQuery();
        if(rs.next()){
            nomedestinatario = rs.getString(1);
            

        }
        
        
        
    } catch (Exception e) {
    }
    
    
    
    
    
}
    
    /**
     * Creates new form TelaTransferencia
     */
    public TelaTransferencia() {
        initComponents();
        conexao = ModuloConexao.conector();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcontclientetransfer = new javax.swing.JTextField();
        txtvalortransfer = new javax.swing.JTextField();
        BotaoTransferir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSFERIR");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("USUÁRIO:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("INFORME A CONTA DO DESTINATARIO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("INFORME O VALOR DESEJADO:");

        txtcontclientetransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontclientetransferActionPerformed(evt);
            }
        });

        txtvalortransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalortransferActionPerformed(evt);
            }
        });

        BotaoTransferir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoTransferir.setForeground(new java.awt.Color(0, 0, 204));
        BotaoTransferir.setText("TRANSFEIR");
        BotaoTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTransferirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("TRANSFERIR");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone-cifrao.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone-transferir.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontclientetransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoTransferir))
                                .addComponent(txtvalortransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel9))
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel7)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontclientetransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txtvalortransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(172, 172, 172))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTransferirActionPerformed
        if(txtcontclientetransfer.getText().equals("") && txtvalortransfer.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os dados corretamente!");
            
            
        } else {
            ConsultaSaldo();
            if (saldo < 0 || saldo < Double.parseDouble(txtvalortransfer.getText())){
                JOptionPane.showMessageDialog(null, "Você não tem saldo suficiente!");
                
                
                
                
            } else {
                saldofinal = saldo - Double.parseDouble(txtvalortransfer.getText());
                Retirando();
                contadestino();
                valordeposito = saldocontadestino + Double.parseDouble(txtvalortransfer.getText());
                adicionando();
                pegandonome();

                JOptionPane.showMessageDialog(null, "Transferência realizada com sucesso!! \n"
                        + "Destinatário: "+ nomedestinatario);
                txtcontclientetransfer.setText("");
                txtvalortransfer.setText("");
            
        }
            
        }


    }//GEN-LAST:event_BotaoTransferirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        TelaAcesso telaacess = new TelaAcesso();
        telaacess.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtvalortransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalortransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalortransferActionPerformed

    private void txtcontclientetransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontclientetransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontclientetransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTransferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoTransferir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcontclientetransfer;
    private javax.swing.JTextField txtvalortransfer;
    // End of variables declaration//GEN-END:variables
}
